spring:
  application:
    name: smart-home-automation-system
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jackson:
    time-zone: UTC
    date-format: com.smarthome.util.ISO8601DateFormat
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC


server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api/v1


logging:
  level:
    root: INFO
    com.shas.smart_home_automation_system: DEBUG
    org.springframework.security: DEBUG