apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-home-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-home-app
  template:
    metadata:
      labels:
        app: smart-home-app
    spec:
      containers:
        - name: smart-home-app
          image: rupaldraft/smart-home-automation:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://shas-postgres:5432/smart_home"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              value: "shas-redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
